### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by funkedavid82** [STAT545-UBC-students/hw01-rasiimwe#1]
Peer-Review HW-01 for rasiimwe
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark: |  |  |
**Presentation: graphs**    | :heavy_check_mark: |  |  |
**Presentation: tables**    | :heavy_check_mark: |   |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Remarks:

- *This work seems great to me and I have no comment on where to improve."*
- *I learned different plotting styles and syntaxes, and I think this work goes  beyond my thought, I am happy I get to see this work to improve my plotting skills *
- *I have always used facet_wrap, but I understood it better from this work*
- *Hey @rasiimwe  I hope I get to review your work some other time to learn more, good job*
- *Maybe you do/don't know that you can categorize quantitative variables and use them as you would use categorical variables, e.g. say we have 5 groups of lifeExp, and this can be used to make a boxplot with gdpPercap*

*Smiles*

**Comment by rasiimwe** [comment]
Thanks for the kind, helpful and positive criticisms. I have taken note of the helpful pointers on how best to work with quantitative variables and will implement them in my next assignments. 

Many thanks, @funkedavid82
