### ISSUE TITLE
Peer-Review HW-01 for @rasiimwe

### ISSUE THREAD

**Issue by zeeva85** [STAT545-UBC-students/hw01-rasiimwe#2]
Peer-Review HW-01 for @rasiimwe 
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|:-----:|:-----:|:-----:|
**Coding style**                   |:heavy_check_mark:|||
**Coding strategy**             |:heavy_check_mark:|||
**Presentation: graphs**     |:heavy_check_mark: |||
**Presentation: tables**      |:heavy_check_mark:|||
**Achievement, creativity** |:heavy_check_mark: |||
**Ease of access**               |:heavy_check_mark: |||

Remarks:

- *Elaborate on above, esp. for "needs work."*

The coding style was good and the strategy for coding was good. Everything was readable. The data presentation made sense and was in the right flow of order, very systematic exploration.

- *Some specific praise?*

This is really good work. WELL DONE !! :+1:. The readme markdown was clean and presentable. The data exploration was complete and through. 

- *Something I learned?* 

I definitely learned how to use the `xyplot` (see below). There is some more advance parameters in your functions that I would be having a deeper look and learning to use, a particularly useful one is the `grid = TRUE ` that I couldn't figure out when I was trying the `xyplot` that is an useful visual aid. Looking at how you used `facet_wrap()`, it helped me understand the other review that I was done with. I now understand what was going on there and it made more sense . 

```
xyplot(gdpPercap ~ lifeExp | factor(year), dataset,subset = year %in% c(1952, 2007),scales = list(x = list(log = 10, equispaced.log = FALSE)),group = continent, auto.key = list(space = "bottom", cex=0.8, just = 2.2,columns = 4),par.settings = params)
```
- *Specific constructive criticism?*

1. There isn't much to say, it was almost a flawless homework. I will however try to give one for the sake of this section, check spelling mistake especially on main page that visitors land on (`readme.md`)so it looks professional, unless you explicitly meant it, you did:-

I am not a _**fun**_ of sea food but I want to try 🐙 😉

*Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.*

1. I tried a couple of times to get the table of contents with my readme.md and coudnt really figure it out, it just refused to go to that subsection and some had some broken links, yours is nicely done.  Good job on those, definately need to look at your code learn employ those and update my `readme.md`. 

2. I had a look at John Grubber markdown  syntax but I needed more time to understand them. However, when I looked at your `readme.md`, because it was an example by itself which I could play around with, it was much easier to understand than reading the John Grubbers manual. 

Kudos 🥇, well done and Thank you @rasiimwe 
>Seevasant Indran

**Comment by rasiimwe** [comment]
Hi @zeeva85 

Thanks for the kind, helpful and positive criticisms. I have taken note of the helpful pointers and glad we have the opportunity to learn from each other through these reviews. 

Many thanks - have an awesome weekend!
