### ISSUE TITLE
hw01-TA

### ISSUE THREAD

**Issue by sherrie9** [STAT545-UBC-students/hw01-rasiimwe#3]
Outstanding work!

Amazing and beautiful introduction in the Readme. 

Your data exploration has gone above and beyond. Code is simple and easy to read with substantial amount of comments. You explained each step of analysis and commented on the results nicely. Good use of various tools and plots. Only thing is the x-axis label on the histogram is a bit hard to read. It will be better if the plot is zoomed in a little. 
But overall really good job!

**Comment by rasiimwe** [comment]
@sherrie9 

Hi Sherrie,
Thanks for your kind, helpful and positive criticisms. I have taken note of the helpful pointers and will try to provide readable labels on my plots for my subsequent assignments. 

Many thanks & have a great weekend!
